# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
url:            "https://arbolitoloco.github.io/uw2020"

# Author
author:
  name:         Laura Rocha Prado
  url:          https://laura.rochaprado.com
  email:        rochaprado@wisc.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
